name: Build and Upload ZIP

on:
  push:
    branches:
      - master  # Vagy main, ha azt használod

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build and publish the application
      - name: Build and Publish
        run: dotnet publish -c Release -r win-x64 --self-contained true -o output

      # Create release directory if it doesn't exist
      - name: Create release directory
        run: |
          if (-not (Test-Path -Path "./release")) {
            New-Item -ItemType Directory -Force -Path "./release"
          }

      # Create a ZIP file containing the published app (exe + dlls)
      - name: Create ZIP file
        run: |
          Compress-Archive -Path output/* -DestinationPath ./release/ToDoApp.zip

      # Create a new version tag based on the commit hash
      - name: Create new version tag
        id: create_tag
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"

      # Upload the ZIP file to GitHub Release
      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/ToDoApp.zip
          tag_name: v${{ steps.create_tag.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
