name: Build Avalonia App

on:
  push:
    branches:
      - master  # Vagy ha a "main" branch-et használod, írd át

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Vagy használd a projektednek megfelelő verziót

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -r win-x64 --self-contained true -o output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AvaloniaApp
          path: output/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
