name: Avalonia Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Vagy az Avalonia projekthez használt verzió

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build Avalonia project
        run: dotnet build --configuration Release --no-restore

      - name: Publish Avalonia App
        run: dotnet publish -c Release -r win-x64 --self-contained true -o output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Avalonia-Windows-Build
          path: output/
